/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luism
 */
public class Gestion_Equipo extends javax.swing.JFrame {

    DefaultTableModel tabla = new DefaultTableModel();
    public static String equipo = "";

    /**
     * Creates new form Gestion_Equipo
     */
    public Gestion_Equipo() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Usuario " + Login.user + ".");
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icono);

        tabla.addColumn("ID");
        tabla.addColumn("Tipo");
        tabla.addColumn("Marca");
        tabla.addColumn("Modelo");
        tabla.addColumn("Num Serie");
        tabla.addColumn("Fecha de Ingreso");
        tabla.addColumn("Status");
        tabla.setRowCount(0);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from equipos");
            ResultSet rs = pst.executeQuery();
            String datos[] = new String[7];

            while (rs.next()) {

                datos[0] = rs.getString("id_equipo");
                datos[1] = rs.getString("tipo_equipo");
                datos[2] = rs.getString("marca");
                datos[3] = rs.getString("modelo");
                datos[4] = rs.getString("num_serie");
                datos[5] = rs.getString("dia_ingreso") + ("/") + rs.getString("mes_ingreso") + ("/") + rs.getString("annio_ingreso");
                datos[6] = rs.getString("status");
                tabla.addRow(datos);
            }
            tabla_equipos.setModel(tabla);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al cargar la tabla");
        }

    }

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_status = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_equipos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        boton_mostrar_info = new javax.swing.JButton();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Equipos Registrados");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(820, 450));
        setPreferredSize(new java.awt.Dimension(820, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nuevo Ingreso", "Revisado", "En reparacion", "Reparado", "Entregado" }));
        combo_status.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_statusItemStateChanged(evt);
            }
        });
        getContentPane().add(combo_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 55, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Equipos Registrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 11, -1, -1));

        tabla_equipos = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int col){
                for(int i = 0; i<tabla_equipos.getRowCount(); i++){
                    if(row==i){
                        return false;
                    }
                }
                return true;
            }
        };
        tabla_equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_equipos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 89, 754, 188));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filtrar por satatus");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 55, -1, -1));

        jLabel11.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel11.setText("Data System");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        boton_mostrar_info.setText("Mostrar");
        boton_mostrar_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mostrar_infoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_mostrar_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 100, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Filtrar Equipos por status
    private void combo_statusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_statusItemStateChanged

        tabla.setRowCount(0);
        tabla.setColumnCount(0);

        String seleccion = new String(combo_status.getSelectedItem().toString());
        String query = "";

        try {
            Connection cn = Conexion.conectar();

            if (seleccion.equals("Todos")) {
                query = "select id_equipo, tipo_equipo, marca, modelo, num_serie, dia_ingreso, mes_ingreso, annio_ingreso, status from equipos";
            } else {
                query = "select id_equipo, tipo_equipo, marca, modelo, num_serie, dia_ingreso, mes_ingreso, annio_ingreso, status from equipos where status = '" + seleccion + "'";
            }

            PreparedStatement pst = cn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel tabla2 = new DefaultTableModel();

            String datos[] = new String[7];
            tabla2.addColumn("ID");
            tabla2.addColumn("Tipo");
            tabla2.addColumn("Marca");
            tabla2.addColumn("Modelo");
            tabla2.addColumn("Num Serie");
            tabla2.addColumn("Fecha de Ingreso");
            tabla2.addColumn("Status");
            tabla2.setRowCount(0);

            while (rs.next()) {

                datos[0] = rs.getString("id_equipo");
                datos[1] = rs.getString("tipo_equipo");
                datos[2] = rs.getString("marca");
                datos[3] = rs.getString("modelo");
                datos[4] = rs.getString("num_serie");
                datos[5] = rs.getString("dia_ingreso") + ("/") + rs.getString("mes_ingreso") + ("/") + rs.getString("annio_ingreso");
                datos[6] = rs.getString("status");
                tabla2.addRow(datos);
            }
            tabla_equipos.setModel(tabla2);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al filtrar " + e);
        }


    }//GEN-LAST:event_combo_statusItemStateChanged

    private void boton_mostrar_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mostrar_infoActionPerformed

        new Vista_Tecnico().setVisible(true);

        equipo = (String) tabla_equipos.getValueAt(tabla_equipos.getSelectedRow(), 0);


    }//GEN-LAST:event_boton_mostrar_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_mostrar_info;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTable tabla_equipos;
    // End of variables declaration//GEN-END:variables
}
