/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author luism
 */
public class Info_Equipo extends javax.swing.JFrame {

    /**
     * Creates new form Info_Equipo
     */
    public Info_Equipo() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Usuario " + Login.user + ".");
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icono);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from equipos where id_equipo = " + Info_Cliente.equipo2);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                txt_id.setText(rs.getString("id_equipo"));
                combo_tipo_equipo.setSelectedItem(rs.getString("tipo_equipo"));
                combo_marca_equipo.setSelectedItem(rs.getString("marca"));
                txt_modelo_equipo.setText(rs.getString("modelo"));
                txt_num_serie.setText(rs.getString("num_serie"));
                txt_fecha.setText(rs.getString("dia_ingreso") + ("/") + rs.getString("mes_ingreso") + ("/") + rs.getString("annio_ingreso"));
                combo_status_equipo.setSelectedItem(rs.getString("status"));
                txt_ultima_modificacion.setText(rs.getString("ultima_modificacion"));
                jTextArea_observaciones.setText(rs.getString("observaciones"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la informacion");

        }

    }

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_observaciones = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_comentarios_tecnico = new javax.swing.JTextArea();
        combo_tipo_equipo = new javax.swing.JComboBox<>();
        combo_marca_equipo = new javax.swing.JComboBox<>();
        txt_num_serie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo_status_equipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        boton_Actualizar = new javax.swing.JButton();
        txt_ultima_modificacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_modelo_equipo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del Equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 11, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de Serie");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 218, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ultima modificacion por:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 468, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de ingreso");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 282, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 343, -1, -1));

        jTextArea_observaciones.setColumns(20);
        jTextArea_observaciones.setRows(5);
        jScrollPane1.setViewportView(jTextArea_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 113, 292, -1));

        jTextArea_comentarios_tecnico.setEditable(false);
        jTextArea_comentarios_tecnico.setColumns(20);
        jTextArea_comentarios_tecnico.setRows(5);
        jScrollPane2.setViewportView(jTextArea_comentarios_tecnico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 264, 292, -1));

        combo_tipo_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Desktop", "Laptop", "Impresora", "Multifuncional", "Consola" }));
        getContentPane().add(combo_tipo_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 87, -1, -1));

        combo_marca_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Sony", "Dell", "Apple", "Acer", "Samsung", "HP", "Lenovo", "Otra" }));
        getContentPane().add(combo_marca_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 122, 104, -1));

        txt_num_serie.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_num_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 238, 143, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Observaciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Comentarios del tecnico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 241, -1, -1));

        combo_status_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Nuevo Ingreso", "Revisado", "En reparacion", "Reparado", "Entregado" }));
        getContentPane().add(combo_status_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Marca");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 125, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Modelo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 153, -1, -1));

        boton_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boton_Actualizar.setText("Actualizar");
        boton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 380, 101, 37));

        txt_ultima_modificacion.setEditable(false);
        getContentPane().add(txt_ultima_modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 135, -1));

        jLabel11.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel11.setText("Data System");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 509, -1, -1));

        txt_modelo_equipo.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_modelo_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 173, 143, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 59, 20, -1));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 56, 90, -1));

        txt_fecha.setEditable(false);
        txt_fecha.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 302, 143, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -1, 580, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ActualizarActionPerformed

        try {
            Connection cn = Conexion.conectar();

            PreparedStatement pst = cn.prepareStatement("update equipos set tipo_equipo = ?, marca = ?, modelo = ?, num_serie = ?, "
                    + "observaciones = ? status = ?, ultima_modificacion = ? where id_equipo = " + Info_Cliente.equipo2);

            pst.setString(1, (String) combo_tipo_equipo.getSelectedItem());
            pst.setString(2, (String) combo_marca_equipo.getSelectedItem());
            pst.setString(3, txt_modelo_equipo.getText().trim());
            pst.setString(4, txt_num_serie.getText().trim());
            pst.setString(5, jTextArea_observaciones.getText());
            pst.setString(6, (String) combo_status_equipo.getSelectedItem());
            pst.setString(7, Login.user);
            pst.executeUpdate();
            txt_ultima_modificacion.setText(Login.user);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar");
        }

    }//GEN-LAST:event_boton_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_Equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Actualizar;
    private javax.swing.JComboBox<String> combo_marca_equipo;
    private javax.swing.JComboBox<String> combo_status_equipo;
    private javax.swing.JComboBox<String> combo_tipo_equipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_comentarios_tecnico;
    private javax.swing.JTextArea jTextArea_observaciones;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_modelo_equipo;
    private javax.swing.JTextField txt_num_serie;
    private javax.swing.JTextField txt_ultima_modificacion;
    // End of variables declaration//GEN-END:variables
}
