/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luism
 */
public class Info_Cliente extends javax.swing.JFrame {

    DefaultTableModel tabla = new DefaultTableModel();
    public static String equipo2;

    /**
     * Creates new form Info_Cliente
     */
    public Info_Cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Usuario " + Login.user + ".");
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icono);

        String datos[] = new String[4];

        tabla.addColumn("ID");
        tabla.addColumn("Tipo");
        tabla.addColumn("Marca");
        tabla.addColumn("Status");
        tabla.setRowCount(0);

        //llenado de tabla_equipos
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from equipos where id_cliente = " + Gestion_Cliente.cliente);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                datos[0] = rs.getString("id_equipo");
                datos[1] = rs.getString("tipo_equipo");
                datos[2] = rs.getString("marca");
                datos[3] = rs.getString("status");
                tabla.addRow(datos);
            }
            tabla_equipos.setModel(tabla);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la tabla de Info_Cliente ");
        }

        //llenado de la info_cliente
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from clientes where id_cliente = '" + Gestion_Cliente.cliente + " '");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                txt_nombre_cliente.setText(rs.getString("nombre_cliente"));
                txt_email_cliente.setText(rs.getString("email_cliente"));
                txt_telefono_cliente.setText(rs.getString("tel_cliente"));
                txt_direccion_cliente.setText(rs.getString("dir_cliente"));
                txt_ultima_modificacion.setText(rs.getString("ultima_modificacion"));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en llenado de la info del Cliente ");
        }

    }

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre_cliente = new javax.swing.JTextField();
        txt_email_cliente = new javax.swing.JTextField();
        txt_telefono_cliente = new javax.swing.JTextField();
        txt_direccion_cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ultima_modificacion = new javax.swing.JTextField();
        boton_registrar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_equipos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 107, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 165, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 223, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 283, -1, -1));

        txt_nombre_cliente.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 127, 200, -1));

        txt_email_cliente.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_email_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 185, 200, -1));

        txt_telefono_cliente.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_telefono_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 243, 200, -1));

        txt_direccion_cliente.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_direccion_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 303, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ultima modificacion por:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        txt_ultima_modificacion.setEditable(false);
        txt_ultima_modificacion.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_ultima_modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 404, 120, -1));

        boton_registrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boton_registrar.setText("Registrar Equipo");
        boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 294, -1, 70));

        jButton_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 370, 90, 40));

        tabla_equipos = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int col){
                for(int i = 0; i<tabla_equipos.getRowCount(); i++){
                    if(row==i){
                        return false;
                    }
                }
                return true;
            }
        };
        tabla_equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_equiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_equipos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 127, 373, 125));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Equipos Registrados");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 84, -1, -1));

        jLabel8.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel8.setText("Data System");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 485, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 720, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrarActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Equipo().setVisible(true);
            }
        });

    }//GEN-LAST:event_boton_registrarActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed

        //actualizacon de datos
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("update clientes set nombre_cliente = ?, email_cliente = ?, tel_cliente = ?, dir_cliente = ?, ultima_modificacion = ? where id_cliente = " + Gestion_Cliente.cliente);

            pst.setString(1, txt_nombre_cliente.getText().trim());
            pst.setString(2, txt_email_cliente.getText().trim());
            pst.setString(3, txt_telefono_cliente.getText().trim());
            pst.setString(4, txt_direccion_cliente.getText().trim());
            pst.setString(5, Login.user);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Informacion actualizada");

            txt_ultima_modificacion.setText(Login.user);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la actualizacion de datos del cliente");
        }

    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void tabla_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_equiposMouseClicked

        if (evt.getClickCount() == 2) {
            new Info_Equipo().setVisible(true);

            equipo2 = (String) tabla.getValueAt(tabla_equipos.getSelectedRow(), 0);
        }

    }//GEN-LAST:event_tabla_equiposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Info_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_registrar;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTable tabla_equipos;
    private javax.swing.JTextField txt_direccion_cliente;
    private javax.swing.JTextField txt_email_cliente;
    private javax.swing.JTextField txt_nombre_cliente;
    private javax.swing.JTextField txt_telefono_cliente;
    private javax.swing.JTextField txt_ultima_modificacion;
    // End of variables declaration//GEN-END:variables
}
