/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author luism
 */
public class Tecnico extends javax.swing.JFrame {

    /**
     * Creates new form Tecnico
     */
    public Tecnico() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Usuario " + Login.user + ".");
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        label_wallpaper.setIcon(icono);

    }

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boton_gestionar = new javax.swing.JButton();
        boton_graf_status = new javax.swing.JButton();
        boton_graf_marcas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Panel Tecnico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 11, -1, -1));

        boton_gestionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boton_gestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apoyo-tecnico.png"))); // NOI18N
        boton_gestionar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        boton_gestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_gestionarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 110, 140, 80));

        boton_graf_status.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boton_graf_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        boton_graf_status.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        boton_graf_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_graf_statusActionPerformed(evt);
            }
        });
        getContentPane().add(boton_graf_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 110, 130, 80));

        boton_graf_marcas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boton_graf_marcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        boton_graf_marcas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        boton_graf_marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_graf_marcasActionPerformed(evt);
            }
        });
        getContentPane().add(boton_graf_marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 110, 130, 80));

        jLabel8.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel8.setText("Data System");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 267, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Grafica por Marcas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Grafica por Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestios de Equipos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -2, 640, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_gestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_gestionarActionPerformed
        new Gestion_Equipo().setVisible(true);
    }//GEN-LAST:event_boton_gestionarActionPerformed

    private void boton_graf_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_graf_statusActionPerformed
        new Grafica_Status_Equipos().setVisible(true);
    }//GEN-LAST:event_boton_graf_statusActionPerformed

    private void boton_graf_marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_graf_marcasActionPerformed
        new Grafica_Marcas().setVisible(true);
    }//GEN-LAST:event_boton_graf_marcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_gestionar;
    private javax.swing.JButton boton_graf_marcas;
    private javax.swing.JButton boton_graf_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_wallpaper;
    // End of variables declaration//GEN-END:variables

}
